### PR TITLE
Testing on rails 5, this seems to work with new AS

### PR DESCRIPTION
**Pull request by inlineblock**

### CODE REVIEW

**Comment by nelsonwittwer** [comment]
@localshred - I'll give you a buffalo nickel if you merge this in.

**Comment by inlineblock** [comment]
I'm gonna fork this and rename it FREE-SA and free it from the tyranny of a someone who open sources code and doesn't maintain or respond to PR's

**Comment by localshred** [comment]
@nelsonwittwer sorry just saw this. Send me your rubygems username and I'll add you as owner.

**Comment by inlineblock** [comment]
sure when i make the PR its ignored, but then nelson mentions it, you merge it.

**Pull request merged**
